version: '2.3'
services:
  zookeeper:
    image: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
     - "9092:9092"
    environment:
     - KAFKA_ADVERTISED_HOST_NAME=localhost
     - KAFKA_CREATE_TOPICS=test:1:1,topic1:1:1:compact
     - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
     - KAFKA_ADVERTISED_PORT=9092
    links: 
     - "zookeeper"
